import { StyleSheet } from 'react-native';
import { fonts } from '../../../constants';

export const Style = StyleSheet.create({
  item: {
    paddingTop: 100,
    paddingHorizontal: 15,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 10,
  },
  image: {
    position: 'absolute',
    left: '50%',
    top: -20,
    transform: [{ translateX: -75 }],
    zIndex: 5,
  },
  itemInner: {
    paddingHorizontal: 25,
    paddingTop: 50,
    paddingBottom: 25,
    backgroundColor: '#ffffff',
  },
  isNewWrap: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  isNew: {
    position: 'relative',
    width: 90,
    height: 18,
    borderTopWidth: 9,
    borderTopColor: '#EBC050',
    borderBottomWidth: 9,
    borderBottomColor: '#EBC050',
    borderLeftWidth: 4,
    borderLeftColor: 'transparent',
    borderRightWidth: 4,
    borderRightColor: 'transparent',
    marginBottom: 10,
    zIndex: 0,
  },
  isPaying: {
    position: 'relative',
    width: 90,
    height: 18,
    borderTopWidth: 9,
    borderTopColor: '#ED8C7E',
    borderBottomWidth: 9,
    borderBottomColor: '#ED8C7E',
    borderLeftWidth: 4,
    borderLeftColor: 'transparent',
    borderRightWidth: 4,
    borderRightColor: 'transparent',
    marginBottom: 10,
    zIndex: 0,
  },
  isNull: {
    display: 'none',
  },
  isNewLabel: {
    position: 'absolute',
    width: '100%',
    top: -7,
    // left: 5.5,
    fontSize: 12,
    color: '#ffffff',
    textAlign: 'center',
    zIndex: 2,
  },
  h2: {
    fontFamily: fonts.RobotoSlabBold,
    fontSize: 26,
    color: '#414555',
    textAlign: 'center',
    marginBottom: 20,
  },
  del: {
    fontSize: 18,
    color: '#67A960',
    textAlign: 'center',
    textDecorationLine: 'line-through',
  },
  cost: {
    fontFamily: fonts.RobotoSlabBold,
    fontSize: 25,
    color: '#67a960',
    textAlign: 'center',
    marginBottom: 20,
  },
  desc: {
    paddingVertical: 20,
    // paddingHorizontal: 5,
    fontSize: 14,
    color: '#54575a',
    textAlign: 'center',
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    color: '#54575a',
    marginBottom: 20,
  },
  table: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 20,
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
    // justifyContent: "space-between"
  },
  col1: {
    width: '60%',
    textAlign: 'left',
    fontSize: 14,
    color: '#54575a',
    borderWidth: 1,
    borderStyle: 'dotted',
    borderColor: 'transparent',
    borderBottomColor: '#d6d6d6',
    borderTopColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  col2: {
    width: '40%',
    textAlign: 'left',
    fontSize: 14,
    color: '#54575a',
  },
  colLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    color: '#979EA6',
    paddingBottom: 5,
  },
  dots: {
    opacity: 0.9,
  },
});
